// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtafhiysrqyoybkramau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0YWZoaXlzcnF5b3lia3JhbWF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODk1NzksImV4cCI6MjA2NjQ2NTU3OX0.MeHk5OGPNFqaQNZUPfwpddhS22i2qlMPq9rlPiyqbJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});